### ISSUE TITLE
Backup user

### ISSUE THREAD

**Issue by joeyboon** [sveeke/SimpleDebianWebserver#19]
While using your script I was prompted to create a backup user. I thought it was smart to name this user backup (not knowing Debian already has a default user named backup). Maby you can prompt the user not to use backup as a username? Thanks! :)

**Comment by sveeke** [comment]
Yeah you are right, it's rather unclear. I'll make a notice that appears if users choose 'backup'. Thanks for the feedback!

**Comment by sveeke** [comment]
Fixed in release 1.1-beta.1

# Choose username backup account
while true
	do
		read -p "$(echo -e "${white}Enter backup account username:         		"${green})" BACKUPUSER
			[ "$BACKUPUSER" != "backup" ] && break
			echo
			echo
			echo -e "${red}****************************************************"
			echo -e "${red}User 'backup' is a system account and can't be used."
			echo -e "${red}****************************************************"
        echo
	done
